In [4]:
import Base
include("fastICA.jl")
using LinearAlgebra
using Statistics

In [17]:
A= [40. 10. ; 120. 399. ;50. 300. ]
#B = fastICA.eigen_decomposition(A)
#A= [40. 10. 50. ; 120. 399. 300.]
#corrA = fastICA.correlation_matrix(A)
#covA = fastICA.covariance_matrix(corrA) 

2×2 Array{Float64,2}:
 0.4     0.3098
 0.3098  0.4   

In [19]:
#broadcast(+,  eps(0.3), B.values)
B.vectors

2×2 Array{Float64,2}:
  0.707107  -0.707107
 -0.707107  -0.707107

In [ ]:
 eps(0.3)

No caso de eigenvalues negativos nao é possivel fazer a raiz de um número sem converter para complexo, como fazer?

In [14]:
(sqrt(inv(Diagonal(broadcast(+,  eps(0.3), B.values)))) * B.vectors') * A


DimensionMismatch: DimensionMismatch("A has dimensions (2,2) but B has dimensions (3,2)")

In [5]:
fastICA.whiten_data(A)

DimensionMismatch: DimensionMismatch("A has dimensions (3,3) but B has dimensions (2,3)")

In [ ]:
(Diagonal(B.values .^ (-1/2)) * B.vectors') * A

In [ ]:
b = Array{Float64,1}


In [13]:
 w = rand(3)

3-element Array{Float64,1}:
 0.20388968451427147
 0.8359983698777036 
 0.6294164427236075 

In [5]:
size(w,2)

1

In [15]:
using LinearAlgebra
normalize!(w,1);
sum(w)

1.0

In [49]:
test = [2. 3. 4. ];
test1 = [1. 2. 3.];
TEST = hcat(test',test1')

3×2 Array{Float64,2}:
 2.0  1.0
 3.0  2.0
 4.0  3.0

In [17]:
size(test)

(2, 3)

In [60]:
test = [ 1 2 4; 3 4 6]
w = rand(2)

tanh.(w' * test)'.^2



3×1 Array{Float64,2}:
 0.5637236678191084
 0.9137559297702136
 0.9977400075437253

In [62]:
ones(10)

10-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [66]:
m = 3
nic = 2 
 W = zeros(m,nic)

3×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [68]:
W = zeros(4,4)
for i = 1 : 4
    w= view(W,:,i)
    w[i] = 1
end
W

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [6]:
using LinearAlgebra
W = rand(5,4)
w=view(W, :, 1)


5-element view(::Array{Float64,2}, :, 1) with eltype Float64:
 0.7114112542344158 
 0.9769675477432227 
 0.38111266304338853
 0.20846236460351353
 0.5223880282624334 

In [7]:
Wp = Array{Float64}(undef,5,4)
copyto!(Wp,W)

5×4 Array{Float64,2}:
 0.711411  0.490437  0.928054  0.288399 
 0.976968  0.764116  0.499409  0.854927 
 0.381113  0.309512  0.613873  0.308536 
 0.208462  0.304537  0.875672  0.0267567
 0.522388  0.825009  0.103254  0.929528 

In [14]:
(W'*W).^(-1/2)

4×4 Array{Float64,2}:
 0.721281  0.765203  0.78602   0.778701
 0.765203  0.768417  0.851682  0.774934
 0.78602   0.851682  0.664456  0.998295
 0.778701  0.774934  0.998295  0.750796

In [15]:
chg = maximum(abs.(abs.(diag(W*Wp')) .- 1.0))

1.5186490606462972